package com.example.sandeep.samplegreendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.sandeep.samplegreendao.db.Teacher;
import com.example.sandeep.samplegreendao.db.Student;

import com.example.sandeep.samplegreendao.db.TeacherDao;
import com.example.sandeep.samplegreendao.db.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teacherDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final TeacherDao teacherDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDao = new TeacherDao(teacherDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(Teacher.class, teacherDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        teacherDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
