package com.example.sandeep.samplegreendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "STUDENT".
 */
@Entity
public class Student {
    private String name;
    private String f_name;
    private String s_class;

    @Id
    private String roll_no;

    @Generated
    public Student() {
    }

    public Student(String roll_no) {
        this.roll_no = roll_no;
    }

    @Generated
    public Student(String name, String f_name, String s_class, String roll_no) {
        this.name = name;
        this.f_name = f_name;
        this.s_class = s_class;
        this.roll_no = roll_no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getF_name() {
        return f_name;
    }

    public void setF_name(String f_name) {
        this.f_name = f_name;
    }

    public String getS_class() {
        return s_class;
    }

    public void setS_class(String s_class) {
        this.s_class = s_class;
    }

    public String getRoll_no() {
        return roll_no;
    }

    public void setRoll_no(String roll_no) {
        this.roll_no = roll_no;
    }

}
