package com.example.sandeep.samplegreendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TEACHER".
 */
@Entity
public class Teacher {
    private String name;
    private String subject;
    private String rating;

    @Id
    private String teacher_id;

    @Generated
    public Teacher() {
    }

    public Teacher(String teacher_id) {
        this.teacher_id = teacher_id;
    }

    @Generated
    public Teacher(String name, String subject, String rating, String teacher_id) {
        this.name = name;
        this.subject = subject;
        this.rating = rating;
        this.teacher_id = teacher_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public String getTeacher_id() {
        return teacher_id;
    }

    public void setTeacher_id(String teacher_id) {
        this.teacher_id = teacher_id;
    }

}
